version: 1
formatters:
  console:
    format: '%(asctime)s [%(levelname)s][%(module)s][%(funcName)s]%(message)s'
  file:
    format: '%(asctime)s [%(levelname)s][%(module)s][%(funcName)s]%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: file
    filename: log.log

loggers:
  simpleLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
